universe = parallel
log    =    log/q4_1-chtc_$(Cluster)_$(ProcId).log
error  =  error/q4_1-chtc_$(Cluster)_$(ProcId).err
output = output/q4_1-chtc_$(Cluster)_$(ProcId).out




machine_count=1


arguments = ./file$(ProcId)/

executable = ./hw4_5.sh

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = http://proxy.chtc.wisc.edu/SQUID/chtc/R402.tar.gz,q3_1.R, /home/groups/STAT605/boss/cB58_Lyman_break.fit,/home/groups/STAT605/boss/tgz/3586.tgz,/home/groups/STAT605/boss/tgz/3587.tgz,/home/groups/STAT605/boss/tgz/3588.tgz,/home/groups/STAT605/boss/tgz/3589.tgz,/home/groups/STAT605/boss/tgz/3590.tgz

request_cpus = 3
request_memory = 2GB
request_disk = 2000MB

queue