universe = vanilla
log    =    log/q3_1-chtc_$(Cluster)_$(Process).log
error  =  error/q3_1-chtc_$(Cluster)_$(Process).err
output = output/q3_1-chtc_$(Cluster)_$(Process).out


executable = ./q3_1.sh


should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = http://proxy.chtc.wisc.edu/SQUID/chtc/R402.tar.gz,q3_1.R, /home/groups/STAT605/boss/cB58_Lyman_break.fit,/home/groups/STAT605/boss/tgz/3586.tgz

request_cpus = 2
request_memory = 2GB
request_disk = 300MB

queue 3